name: clavus
base: core22
version: '1.1.0'
license: MIT
contact: pietro.mobrici@gmail.com
website: https://github.com/peter-mbx/clavus
source-code: https://github.com/peter-mbx/clavus

summary: Simplify the management of configurations on your machine
description: |
  A lightweight command-line tool designed for anyone in the tech field, specially for IT consultants or professionals managing multiple clients environments. This tool simplifies the management of configurations on your machine, allowing you to configure your environment and load the necessary resources, like files and/or commands.

grade: stable
confinement: classic

architectures:
  - build-on: [amd64]
    build-for: [all]

parts:
  clavus:
    plugin: rust
    source: https://github.com/peter-mbx/clavus.git
    source-tag: '1.1.0'
    build-packages:
      - build-essential
    stage-packages:
      - libc-dev

apps:
  clavus:
    command: bin/clavus
